MoneyBankers/Pages/Payment/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using MoneyBankers.Data;
using MoneyBankers.Models;

namespace MoneyBankers.Pages.Payment
{
    public class CreateModel : PageModel
    {
        private readonly MoneyBankers.Data.MoneyBankersContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        public CreateModel(MoneyBankers.Data.MoneyBankersContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }
        //

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Models.Payment Payment { get; set; }

        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            string userName = _userManager.GetUserName(User);
            ApplicationUser sender = _context.Users.SingleOrDefault(u=>u.Email==userName);
            ApplicationUser receiver = _context.Users.SingleOrDefault(u => u.Email == Payment.Receiver);
            if (receiver != null)
            {
                if (sender.BankBalance < Payment.Amount || sender.BankBalance <= 0)
                {
                    TempData["message"] = "Low bank balance";
                }
                else
                {
                    receiver.BankBalance = receiver.BankBalance + Payment.Amount;
                    sender.BankBalance = sender.BankBalance - Payment.Amount;
                    Payment.Sender = userName;
                    _context.Payment.Add(Payment);
                    await _context.SaveChangesAsync();
                    return RedirectToPage("./Index");
                }
            }
            else
            {
                TempData["message"] = "No such receipient";
            }
            return Page();
        }
    }
}

MoneyBankers/Pages/Payment/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using MoneyBankers.Data;
using MoneyBankers.Models;

namespace MoneyBankers.Pages.Payment
{
    public class DeleteModel : PageModel
    {
        private readonly MoneyBankers.Data.MoneyBankersContext _context;

        public DeleteModel(MoneyBankers.Data.MoneyBankersContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Models.Payment Payment { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Payment = await _context.Payment.FirstOrDefaultAsync(m => m.ID == id);

            if (Payment == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Payment = await _context.Payment.FindAsync(id);

            if (Payment != null)
            {
                _context.Payment.Remove(Payment);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

MoneyBankers/Pages/Payment/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using MoneyBankers.Data;
using MoneyBankers.Models;

namespace MoneyBankers.Pages.Payment
{
    public class DetailsModel : PageModel
    {
        private readonly MoneyBankers.Data.MoneyBankersContext _context;

        public DetailsModel(MoneyBankers.Data.MoneyBankersContext context)
        {
            _context = context;
        }

        public Models.Payment Payment { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Payment = await _context.Payment.FirstOrDefaultAsync(m => m.ID == id);

            if (Payment == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

MoneyBankers/Pages/Payment/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MoneyBankers.Data;
using MoneyBankers.Models;

namespace MoneyBankers.Pages.Payment
{
    public class EditModel : PageModel
    {
        private readonly MoneyBankers.Data.MoneyBankersContext _context;

        public EditModel(MoneyBankers.Data.MoneyBankersContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Models.Payment Payment { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Payment = await _context.Payment.FirstOrDefaultAsync(m => m.ID == id);

            if (Payment == null)
            {
                return NotFound();
            }
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(Payment).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!PaymentExists(Payment.ID))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool PaymentExists(int id)
        {
            return _context.Payment.Any(e => e.ID == id);
        }
    }
}

MoneyBankers/Pages/Roles/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MoneyBankers.Models;

namespace MoneyBankers.Pages.Roles
{
    public class CreateModel : PageModel
    {
        private readonly RoleManager<ApplicationRole> _roleManager;

        public CreateModel(RoleManager<ApplicationRole> roleManager)
        {
            _roleManager = roleManager;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public ApplicationRole ApplicationRole { get; set; }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            ApplicationRole.CreatedDate = DateTime.UtcNow;
            ApplicationRole.IPAddress = Request.HttpContext.Connection.RemoteIpAddress.ToString();

            IdentityResult roleRuslt = await _roleManager.CreateAsync(ApplicationRole);

            return RedirectToPage("Index");
        }

    }
}

MoneyBankers/Pages/Roles/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MoneyBankers.Models;

namespace MoneyBankers.Pages.Roles
{
    public class DeleteModel : PageModel
    {
        private readonly RoleManager<ApplicationRole> _roleManager;

        public DeleteModel(RoleManager<ApplicationRole> roleManager)
        {
            _roleManager = roleManager;
        }

        [BindProperty]
        public ApplicationRole ApplicationRole { get; set; }

        public async Task<IActionResult> OnGetAsync(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ApplicationRole = await _roleManager.FindByIdAsync(id);

            if (ApplicationRole == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ApplicationRole = await _roleManager.FindByIdAsync(id);
            IdentityResult roleRuslt = await _roleManager.DeleteAsync(ApplicationRole);

            return RedirectToPage("./Index");

        }

    }
}

MoneyBankers/Pages/Roles/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MoneyBankers.Models;

namespace MoneyBankers.Pages.Roles
{
    public class DetailsModel : PageModel
    {
        private readonly RoleManager<ApplicationRole> _roleManager;

        public DetailsModel(RoleManager<ApplicationRole> roleManager)
        {
            _roleManager = roleManager;
        }

        public ApplicationRole ApplicationRole { get; set; }

        public async Task<IActionResult> OnGetAsync(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ApplicationRole = await _roleManager.FindByIdAsync(id);

            if (ApplicationRole == null)
            {
                return NotFound();
            }
            return Page();
        }

    }
}

MoneyBankers/Pages/Roles/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MoneyBankers.Models;

namespace MoneyBankers.Pages.Roles
{
    public class EditModel : PageModel
    {
        private readonly RoleManager<ApplicationRole> _roleManager;


        public EditModel(RoleManager<ApplicationRole> roleManager)
        {
            _roleManager = roleManager;
        }

        [BindProperty]
        public ApplicationRole ApplicationRole { get; set; }

        public async Task<IActionResult> OnGetAsync(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ApplicationRole = await _roleManager.FindByIdAsync(id);

            if (ApplicationRole == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            ApplicationRole appRole = await _roleManager.FindByIdAsync(ApplicationRole.Id);

            appRole.Id = ApplicationRole.Id;
            appRole.Name = ApplicationRole.Name;
            appRole.Description = ApplicationRole.Description;

            IdentityResult roleRuslt = await _roleManager.UpdateAsync(appRole);

            if (roleRuslt.Succeeded)
            {
                return RedirectToPage("./Index");

            }
            return RedirectToPage("./Index");
        }

    }
}

MoneyBankers/Pages/Roles/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using MoneyBankers.Models;

namespace MoneyBankers.Pages.Roles
{
    public class IndexModel : PageModel
    {
        private readonly RoleManager<ApplicationRole> _roleManager;

        public IndexModel(RoleManager<ApplicationRole> roleManager)
        {
            _roleManager = roleManager;
        }

        public List<ApplicationRole> ApplicationRole { get; set; }

        public async Task OnGetAsync()
        {
            // Get a list of roles
            ApplicationRole = await _roleManager.Roles.ToListAsync();

        }

    }
}

MoneyBankers/Pages/Roles/Manage.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MoneyBankers.Models;

namespace MoneyBankers.Pages.Roles
{
    public class ManageModel : PageModel
    {
        private readonly MoneyBankers.Data.MoneyBankersContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<ApplicationRole> _roleManager;

        public ManageModel(MoneyBankers.Data.MoneyBankersContext context, UserManager<ApplicationUser> userManager, RoleManager<ApplicationRole> roleManager)
        {
            _context = context;
            _userManager = userManager;
            _roleManager = roleManager;
        }

        public SelectList RolesSelectList;
        //contain  a list of roles to populate select box
        public SelectList UsersSelectList;
        // contain  a list of Users to populate select box

        public string selectedrolename { set; get; }
        public string selectedusername { set; get; }
        public string delrolename { set; get; }
        public string delusername { set; get; }

        public int usercountinrole { set; get; }
        public IList<ApplicationRole> Listroles { get; set; }

        public string ListUsersInRole(string rolename)
        {
            // Method - return a string showing a list of users  based on specified role as parameter
            string strListUsersInRole = "";
            string roleid = _roleManager.Roles.SingleOrDefault(u => u.Name == rolename).Id;

            // Get no. of users for each specified role
            var count = _context.UserRoles.Where(u => u.RoleId == roleid).Count();
            usercountinrole = count;

            //Get a list of users for each specified role
            var listusers = _context.UserRoles.Where(u => u.RoleId == roleid);

            foreach (var oParam in listusers)
            {    // loop thru each objects-  get username based on userid and append to the returned string
                var userobj = _context.Users.SingleOrDefault(s => s.Id == oParam.UserId);
                strListUsersInRole += "[" + userobj.UserName + "] ";
            }
            return strListUsersInRole;
        }

        public async Task OnGetAsync()
        {   //HTTPGet  - when form is being loaded
            //get list of roles and users
            IQueryable<string> RoleQuery = from m in _roleManager.Roles orderby m.Name select m.Name;
            IQueryable<string> UsersQuery = from u in _context.Users orderby u.UserName select u.UserName;

            RolesSelectList = new SelectList(await RoleQuery.Distinct().ToListAsync());
            UsersSelectList = new SelectList(await UsersQuery.Distinct().ToListAsync());
            // Get all the roles 
            var roles = from r in _roleManager.Roles
                        select r;
            Listroles = await roles.ToListAsync();
        }


        public async Task<IActionResult> OnPostAsync(string selectedusername, string selectedrolename)
        {
            //When the Assign button is pressed 
            if ((selectedusername == null) || (selectedrolename == null))
            {
                return RedirectToPage("Manage");
            }

            ApplicationUser AppUser = _context.Users.SingleOrDefault(u => u.UserName == selectedusername);
            ApplicationRole AppRole = await _roleManager.FindByNameAsync(selectedrolename);

            IdentityResult roleResult = await _userManager.AddToRoleAsync(AppUser, AppRole.Name);

            if (roleResult.Succeeded)
            {
                TempData["message"] = "Role added to this user successfully";
                return RedirectToPage("Manage");
            }

            return RedirectToPage("Manage");
        }

        public async Task<IActionResult> OnPostDeleteUserRoleAsync(string delusername, string delrolename)
        {
            //When the Delete this user from  Role button is pressed 
            if ((delusername == null) || (delrolename == null))
            {
                return RedirectToPage("Manage");
            }

            ApplicationUser user = _context.Users.Where(u => u.UserName == delusername).FirstOrDefault();

            if (await _userManager.IsInRoleAsync(user, delrolename))
            {
                await _userManager.RemoveFromRoleAsync(user, delrolename);

                TempData["message"] = "Role removed from this user successfully";
            }

            return RedirectToPage("Manage");
        }

    }
}

MoneyBankers/Pages/Roles/Create.cshtml
@page
@model MoneyBankers.Pages.Roles.CreateModel
@{
    ViewData["Title"] = "Create";
}
<h2>Create Role</h2>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ApplicationRole.Name" class="control-label"></label>
                <input asp-for="ApplicationRole.Name" class="form-control" />
                <span asp-validation-for="ApplicationRole.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ApplicationRole.Description" class="control-label"></label>
                <input asp-for="ApplicationRole.Description" class="form-control" />
                <span asp-validation-for="ApplicationRole.Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>
<div>
    <a asp-page="Index">Back to List</a>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MoneyBankers/Pages/Roles/Delete.cshtml
@page
@model MoneyBankers.Pages.Roles.DeleteModel
@{
    ViewData["Title"] = "Delete";
}
<h2>Delete</h2>
<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Application Role</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ApplicationRole.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ApplicationRole.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ApplicationRole.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ApplicationRole.Description)
        </dd>
    </dl>
    <form method="post">
        <input type="hidden" asp-for="ApplicationRole.Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>

MoneyBankers/Pages/Roles/Details.cshtml
@page
@model MoneyBankers.Pages.Roles.DetailsModel
@{
    ViewData["Title"] = "Details";
}
<h2>Details</h2>
<div>
    <h4>ApplicationRole</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ApplicationRole.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ApplicationRole.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ApplicationRole.CreatedDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ApplicationRole.CreatedDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ApplicationRole.IPAddress)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ApplicationRole.IPAddress)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ApplicationRole.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ApplicationRole.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ApplicationRole.NormalizedName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ApplicationRole.NormalizedName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ApplicationRole.ConcurrencyStamp)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ApplicationRole.ConcurrencyStamp)
        </dd>
    </dl>
</div>
<div>
    <a asp-page="./Edit" asp-route-id="@Model.ApplicationRole.Id">Edit</a> |
    <a asp-page="./Index">Back to List</a>
</div>

MoneyBankers/Pages/Roles/Edit.cshtml
@page
@model MoneyBankers.Pages.Roles.EditModel
@{
    ViewData["Title"] = "Edit";
}

<h2>Edit Application Role</h2>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ApplicationRole.Name" class="control-label"></label>
                <input asp-for="ApplicationRole.Name" class="form-control" />
                <span asp-validation-for="ApplicationRole.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ApplicationRole.Description" class="control-label"></label>
                <input asp-for="ApplicationRole.Description" class="form-control" />
                <span asp-validation-for="ApplicationRole.Description" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="ApplicationRole.Id" />

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>

    </div>
</div>

<div>
    <a asp-page="./Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MoneyBankers/Pages/Roles/Index.cshtml
@page
@model MoneyBankers.Pages.Roles.IndexModel

@{
    ViewData["Title"] = "Role Listing";
}
<h2>Role Listing</h2>

<div class="row">
    <div class="col-md-4">
        <a asp-page="Create">[Create New Role]</a> |
        <a asp-page="Manage">[Manage User Roles]</a>
    </div>
</div>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ApplicationRole[0].Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ApplicationRole[0].Description)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.ApplicationRole)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    <a asp-page="./Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-page="./Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-page="./Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

MoneyBankers/Pages/Roles/Manage.cshtml
@page
@model MoneyBankers.Pages.Roles.ManageModel
@{
    ViewData["Title"] = "Manage User Roles";
}
<h2>Role-based Authorization Management</h2>
<div class="row">
    <div class="col-md-4">
        <a asp-page="Create">[Create New Role]</a> |
        <a asp-page="Manage">[Manage User Roles]</a>
    </div>
</div>

@if (TempData["message"] != null)
{
    <p><font color="red">@TempData["message"]</font></p>
}

<h3>[Role View - show the users in each role] </h3>
<hr />
<table class="table">
    <thead>
        <tr>
            <th>Role Name </th>
            <th>Users assigned to this role</th>
            <th>No. of Users</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model.Listroles)
        {
            <tr>
                <td> @Html.DisplayFor(modelItem => item.Name)</td>
                <td> @Model.ListUsersInRole(item.Name)</td>
                <td> @Model.usercountinrole </td>
            </tr>
        }
    </tbody>
</table>

<h3>[Add Role to User]</h3>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            @Html.Label("Select User : ")
            @Html.DropDownListFor(m => m.selectedusername, Model.UsersSelectList, "Select User", new { @class = "form-control" })
            @Html.Label("Assign Role : ")
            @Html.DropDownListFor(m => m.selectedrolename, Model.RolesSelectList, "Select Role", new { @class = "form-control" })
            <br />
            <input type="submit" value="Assign" />
        </form>
    </div>

</div>

<hr />
<h3>[Delete A User from a Role]</h3>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            @Html.Label("Select User : ")
            @Html.DropDownListFor(m => m.delusername, Model.UsersSelectList, "Select User", new { @class = "form-control" })
            @Html.Label("Select Role : ")
            @Html.DropDownListFor(m => m.delrolename, Model.RolesSelectList, "Select Role", new { @class = "form-control" })
            <br />
            <input type="submit" value="Delete this user from Role" asp-page-handler="DeleteUserRole" />
        </form>
    </div>
</div>